//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.22 at 09:38:54 AM BDT 
//


package com.example.adservice;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.adservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.adservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UpdateUserResponse }
     * 
     */
    public UpdateUserResponse createUpdateUserResponse() {
        return new UpdateUserResponse();
    }

    /**
     * Create an instance of {@link GetAllGroupsResponse }
     * 
     */
    public GetAllGroupsResponse createGetAllGroupsResponse() {
        return new GetAllGroupsResponse();
    }

    /**
     * Create an instance of {@link GetAllUsersRequest }
     * 
     */
    public GetAllUsersRequest createGetAllUsersRequest() {
        return new GetAllUsersRequest();
    }

    /**
     * Create an instance of {@link GetAllUsersResponse }
     * 
     */
    public GetAllUsersResponse createGetAllUsersResponse() {
        return new GetAllUsersResponse();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link GetUserDetailsRequest }
     * 
     */
    public GetUserDetailsRequest createGetUserDetailsRequest() {
        return new GetUserDetailsRequest();
    }

    /**
     * Create an instance of {@link GetUserDetailsResponse }
     * 
     */
    public GetUserDetailsResponse createGetUserDetailsResponse() {
        return new GetUserDetailsResponse();
    }

    /**
     * Create an instance of {@link CreateUserRequest }
     * 
     */
    public CreateUserRequest createCreateUserRequest() {
        return new CreateUserRequest();
    }

    /**
     * Create an instance of {@link CreateUserResponse }
     * 
     */
    public CreateUserResponse createCreateUserResponse() {
        return new CreateUserResponse();
    }

    /**
     * Create an instance of {@link UpdateUserRequest }
     * 
     */
    public UpdateUserRequest createUpdateUserRequest() {
        return new UpdateUserRequest();
    }

    /**
     * Create an instance of {@link UpdateUserResponse.UpdatedUser }
     * 
     */
    public UpdateUserResponse.UpdatedUser createUpdateUserResponseUpdatedUser() {
        return new UpdateUserResponse.UpdatedUser();
    }

    /**
     * Create an instance of {@link DeleteUserRequest }
     * 
     */
    public DeleteUserRequest createDeleteUserRequest() {
        return new DeleteUserRequest();
    }

    /**
     * Create an instance of {@link DeleteUserResponse }
     * 
     */
    public DeleteUserResponse createDeleteUserResponse() {
        return new DeleteUserResponse();
    }

    /**
     * Create an instance of {@link EnableUserRequest }
     * 
     */
    public EnableUserRequest createEnableUserRequest() {
        return new EnableUserRequest();
    }

    /**
     * Create an instance of {@link EnableUserResponse }
     * 
     */
    public EnableUserResponse createEnableUserResponse() {
        return new EnableUserResponse();
    }

    /**
     * Create an instance of {@link DisableUserRequest }
     * 
     */
    public DisableUserRequest createDisableUserRequest() {
        return new DisableUserRequest();
    }

    /**
     * Create an instance of {@link DisableUserResponse }
     * 
     */
    public DisableUserResponse createDisableUserResponse() {
        return new DisableUserResponse();
    }

    /**
     * Create an instance of {@link GetAllGroupsRequest }
     * 
     */
    public GetAllGroupsRequest createGetAllGroupsRequest() {
        return new GetAllGroupsRequest();
    }

    /**
     * Create an instance of {@link GetAllGroupsResponse.Group }
     * 
     */
    public GetAllGroupsResponse.Group createGetAllGroupsResponseGroup() {
        return new GetAllGroupsResponse.Group();
    }

    /**
     * Create an instance of {@link AddUserToGroupsRequest }
     * 
     */
    public AddUserToGroupsRequest createAddUserToGroupsRequest() {
        return new AddUserToGroupsRequest();
    }

    /**
     * Create an instance of {@link AddUserToGroupsResponse }
     * 
     */
    public AddUserToGroupsResponse createAddUserToGroupsResponse() {
        return new AddUserToGroupsResponse();
    }

    /**
     * Create an instance of {@link RemoveUserFromGroupsRequest }
     * 
     */
    public RemoveUserFromGroupsRequest createRemoveUserFromGroupsRequest() {
        return new RemoveUserFromGroupsRequest();
    }

    /**
     * Create an instance of {@link RemoveUserFromGroupsResponse }
     * 
     */
    public RemoveUserFromGroupsResponse createRemoveUserFromGroupsResponse() {
        return new RemoveUserFromGroupsResponse();
    }

}
