//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.06 at 10:46:16 AM BDT
//


package com.example.adservice;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for userDetailsDTO complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="userDetailsDTO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="sAMAccountName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="distinguishedName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="userPrincipalName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="objectGUID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="givenName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="sn" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="mail" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="memberOf" type="{http://example.com/adservice}group" maxOccurs="unbounded"/&gt;
 *         &lt;element name="userAccountControl" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "userDetailsDTO", propOrder = {
    "samAccountName",
    "distinguishedName",
    "userPrincipalName",
    "objectGUID",
    "givenName",
    "sn",
    "mail",
    "memberOf",
    "userAccountControl"
})
public class UserDetailsDTO {

    @XmlElement(name = "sAMAccountName", required = true)
    protected String samAccountName;
    @XmlElement(required = true)
    protected String distinguishedName;
    @XmlElement(required = true)
    protected String userPrincipalName;
    @XmlElement(required = true)
    protected String objectGUID;
    @XmlElement(required = true)
    protected String givenName;
    @XmlElement(required = true)
    protected String sn;
    @XmlElement(required = true)
    protected String mail;
    @XmlElement(required = true)
    protected List<Group> memberOf;
    @XmlElement(required = true)
    protected String userAccountControl;

    /**
     * Gets the value of the samAccountName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSAMAccountName() {
        return samAccountName;
    }

    /**
     * Sets the value of the samAccountName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSAMAccountName(String value) {
        this.samAccountName = value;
    }

    /**
     * Gets the value of the distinguishedName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDistinguishedName() {
        return distinguishedName;
    }

    /**
     * Sets the value of the distinguishedName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDistinguishedName(String value) {
        this.distinguishedName = value;
    }

    /**
     * Gets the value of the userPrincipalName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getUserPrincipalName() {
        return userPrincipalName;
    }

    /**
     * Sets the value of the userPrincipalName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setUserPrincipalName(String value) {
        this.userPrincipalName = value;
    }

    /**
     * Gets the value of the objectGUID property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getObjectGUID() {
        return objectGUID;
    }

    /**
     * Sets the value of the objectGUID property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setObjectGUID(String value) {
        this.objectGUID = value;
    }

    /**
     * Gets the value of the givenName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getGivenName() {
        return givenName;
    }

    /**
     * Sets the value of the givenName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setGivenName(String value) {
        this.givenName = value;
    }

    /**
     * Gets the value of the sn property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSn() {
        return sn;
    }

    /**
     * Sets the value of the sn property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSn(String value) {
        this.sn = value;
    }

    /**
     * Gets the value of the mail property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMail() {
        return mail;
    }

    /**
     * Sets the value of the mail property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMail(String value) {
        this.mail = value;
    }

    /**
     * Gets the value of the memberOf property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the memberOf property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMemberOf().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Group }
     *
     *
     */
    public List<Group> getMemberOf() {
        if (memberOf == null) {
            memberOf = new ArrayList<Group>();
        }
        return this.memberOf;
    }

    /**
     * Gets the value of the userAccountControl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserAccountControl() {
        return userAccountControl;
    }

    /**
     * Sets the value of the userAccountControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserAccountControl(String value) {
        this.userAccountControl = value;
    }

}
